### ISSUE TITLE
fine tune the search for names in the autocomplete

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-instance-oebl-pfp#280]
- currently all text fields are searched, reduce to names and alternative names
- think of search terms that allow to further filter results

**Comment by b1rger** [comment]
Related: https://github.com/acdh-oeaw/apis-core-rdf/pull/946

**Comment by sennierer** [comment]
eg searching for "Universität Wien" brings up a lot of hits, but you need to scroll several pages to get to the "local result" thats name == the search term.

**Comment by b1rger** [comment]
6ea320d34bca8912ee8e8bd9bc1c8f6cc351e786 is one approach to fix that - if that works good enough, we can use that for the other entities

**Comment by sennierer** [comment]
look good, closing this
